### PR TITLE
refactoring, readme update, minor UI updates

### PR DESCRIPTION
**Pull request by ReasonSharp**
I've moved the pubkey validation/conversion to hex logic to a separate method in lib folder, used it in places where user's input pubkey needs to be validated, to avoid duplication of the same logic (it was inconsistent). Also helps with consistently storing hex keys into the database as is recommended by NIP-19 (npubs were sometimes stored in bech32 format).

In some places added UI elements to display pubkey input errors.

In middleware also skipping adding rewrite header if host url contains 'localhost'.

### CODE REVIEW

**Comment by ReasonSharp** [comment]
Sorry about the lock file mess, I've restored original versions in last commit.

**Comment by jeremyd** [comment]
@ReasonSharp did you see this?
https://github.com/relaytools/relaycreator/blob/main/app/posts/page.tsx#L408

The bech32 decoder will throw errors about mixed case as well, so I tightened up this regex, and also doing toLowerCase now.. Need to update this PR with the new 'official' regex.. (I grabbed it from the bech32 libs).

**Comment by ReasonSharp** [comment]
Also if you take a look at the `convertOrValidatePubkey` method I added in lib/pubkeyValidation.ts, I'm doing toLowerCase as well - I've seen the change and the rationale elsewhere in the code and included it.

**Comment by jeremyd** [comment]
This looks pretty good, I've merged it into the nip05 branch, did some smoke testing and changed the regex to bech32.  Thanks for this!  It will be in the next release.

https://github.com/relaytools/relaycreator/pull/13

**Pull request merged**
